### ISSUE TITLE
QW-ACT-R7 problem

### ISSUE THREAD

**Issue by DiedeGu** [qualweb/cli#2]
Dear readers, I am running the cli with the basic usage: `qw -u https://google.com/` giving me this error: 

```
Error: Evaluation failed: TypeError: Cannot read property 'length' of undefined
    at QW_ACT_R7.unmappedExecute (webpack://ACTRules/./dist/rules/QW-ACT-R7.js?:43:25)
    at ACTRules.executeNotMappedRules (webpack://ACTRules/./dist/index.js?:141:37)
    at ACTRules.execute (webpack://ACTRules/./dist/index.js?:191:14)
    at __puppeteer_evaluation_script__:3:24
```

I guess I am not even reporting it at the right package, but I would like to know where I could report the issue. Kind Regards

**Comment by carlosapaduarte** [comment]
Dear @DiedeGu,
An update we introduced yesterday broke something. We're working on a fix and we'll update this issue as soon as it published.
Thank you for your input!

**Comment by carlosapaduarte** [comment]
Dear @DiedeGu,
We've pushed a new update that fixes this issue. 
Once again, thanks for the warning!
