### ISSUE TITLE
Using option save-name has no effect

### ISSUE THREAD

**Issue by rimi-itk** [qualweb/cli#7]
Running 

```sh
qw --url https://example.com/ --report-type earl-a --save-name reports.json
```

ignores the `--save-name` option and saves to `https%3A%2F%2Fexample.com%2F_1618586970380.json`, say.

**Comment by joao-vicente** [comment]
Hi! Thank you for noticing the problem. I have already seen the pull request and I will merge it. After that i'll release a new npm version with the fix!
