### ISSUE TITLE
Simple evaluation never ending

### ISSUE THREAD

**Issue by Ornhoj** [qualweb/cli#9]
After a clean install of the CLI 
`$ npm i -g @qualweb/cli`
and doing a test run in NodeJs 14.17.0 with the following command

`$ qw -u https://act-rules.github.io/pages/about/`

The commands have been used in CMD admin mode.

What am I missing / doing wrong?

No output, no feedback, the following screen have been pending for 10 minutes.
![image](https://user-images.githubusercontent.com/1859131/120161484-a8eb2e00-c1f7-11eb-8e7a-8180ed1c49a0.png)

**Comment by carlosapaduarte** [comment]
@Ornhoj thanks from reaching out. Nothing wrong from your part. This was caused by one update from our side that did not reach out to the CLI tool. We just published a new version. If you update to this version the problem should go away.

**Comment by Ornhoj** [comment]
@carlosapaduarte sorry for not responding, I have just rechecked the CLI and the problem has been solved. Thank you for the quick reply and solution.
